language: python
python:
  - "2.6"
  - "2.7"
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -y libopenmpi-dev openmpi-bin openmpi-doc
install:
  - "pip install ."
# command to run tests
script: "mpirun -c 4 python tests/test_pypar.py"
